// index-react.jsx
import React from "react";
import Core from "./index.js";

export class SimpleCrop extends React.Component {
  instance; //组件实例

  constructor(props) {
    super(props);
  }

  //初次渲染
  componentDidMount () {
    this.instance = new Core(this.props);
  }

  //组件属性更新是否需要重新构建组件
  shouldRebuild (prevProps) {
    //title、src、debug、zIndex、noBoldCorner、coverColor、borderColor、borderWidth、coverDraw、borderDraw、visible、cropCallback、uploadCallback、closeCallback
    let build = false;
    if (
      prevProps.maxScale != this.props.maxScale ||
      prevProps.scaleSlider != this.props.scaleSlider ||
      prevProps.cropSizePercent != this.props.cropSizePercent ||
      prevProps.rotateSlider != this.props.rotateSlider ||
      prevProps.startAngle != this.props.startAngle ||
      prevProps.endAngle != this.props.endAngle ||
      prevProps.gapAngle != this.props.gapAngle ||
      prevProps.lineationItemWidth != this.props.lineationItemWidth ||
      prevProps.funcBtns != this.props.funcBtns
    ) {
      build = true;
    }

    if (this.props.size && prevProps.size) {
      if (
        prevProps.size.width != this.props.size.width ||
        prevProps.size.height != this.props.size.height
      ) {
        build = true;
      }
    } else if (this.props.size || prevProps.size) {
      build = true;
    }

    if (this.props.positionOffset && prevProps.positionOffset) {
      if (
        prevProps.positionOffset.top != this.props.positionOffset.top ||
        prevProps.positionOffset.left != this.props.positionOffset.left
      ) {
        build = true;
      }
    } else if (this.props.positionOffset || prevProps.positionOffset) {
      build = true;
    }

    //功能按钮顺序也不能发生变化
    if (this.props.funcBtns && prevProps.funcBtns) {
      for (let i = 0; i < this.props.funcBtns.length; i++) {
        if (prevProps.funcBtns[i] != this.props.funcBtns[i]) {
          build = true;
        }
      }
    }

    return build;
  }

  //更新
  componentDidUpdate (prevProps) {
    if (this.shouldRebuild(prevProps)) {
      if (this.instance) {
        this.instance.$container.removeChild(this.instance.$target);
      }
      this.instance = new Core(this.props);
    } else {
      if (this.instance) {
        if (this.props.visible) {
          this.instance.show();
        } else {
          this.instance.hide();
        }
        if (prevProps.title != this.props.title) {
          this.instance.title = this.props.title;
          this.instance.$title.innerText = this.props.title;
        }
        if (prevProps.src != this.props.src) {
          this.instance.setImage(this.props.src);
        }
        this.instance.debug = this.props.debug;
        if (prevProps.zIndex != this.props.zIndex) {
          this.instance.zIndex = this.props.zIndex;
          this.instance.$target.style.zIndex = this.props.zIndex;
        }
        if (prevProps.borderDraw != this.props.borderDraw) {
          this.instance.borderDraw = this.props.borderDraw.bind(this.instance);
        }
        if (
          prevProps.noBoldCorner != this.props.noBoldCorner ||
          prevProps.coverColor != this.props.coverColor ||
          prevProps.borderColor != this.props.borderColor ||
          prevProps.borderWidth != this.props.borderWidth
        ) {
          this.instance.borderDraw();
        }
        if (prevProps.coverDraw != this.props.coverDraw) {
          this.instance.coverDraw = this.props.coverDraw.bind(this.instance);
          this.instance.borderDraw();
          this.instance.coverDraw();
        }
        if (prevProps.cropCallback != this.props.cropCallback) {
          this.instance.cropCallback = this.props.cropCallback.bind(
            this.instance
          );
        }
        if (prevProps.uploadCallback != this.props.uploadCallback) {
          this.instance.uploadCallback = this.props.uploadCallback.bind(
            this.instance
          );
        }
        if (prevProps.closeCallback != this.props.closeCallback) {
          this.instance.closeCallback = this.props.closeCallback.bind(
            this.instance
          );
        }
      }
    }
  }

  render () {
    return <div />;
  }
}

// index.vue
<template></template>

<script>
import Core from "./index.js";

export default {
  _instance: null, //组件实例

  props: ["cropParams"],

  mounted() {
    this.cropParams.cropCallback = this.cropCallback.bind(this);
    this.cropParams.uploadCallback = this.uploadCallback.bind(this);
    this.cropParams.closeCallback = this.closeCallback.bind(this);
    this.instance = new Core(this.cropParams);
  },

  methods: {
    //关闭回调
    closeCallback() {
      this.$emit("close");
    },
    //上传图片回调
    uploadCallback() {
      var src = this.instance ? this.instance.src : this.cropParams.src;
      this.$emit("upload", src);
    },
    //裁剪回调
    cropCallback() {
      var $resultCanvas = this.instance ? this.instance.$resultCanvas : null;
      this.$emit("crop", $resultCanvas);
    },
    //属性是否发生变化
    hasChanged(names, props) {
      let cur = {};
      let prev = {};
      for (let i = 0; i < names.length; i++) {
        let item = names[i];
        cur[item] = this.cropParams[item];
        prev[item] = props[item];
      }
      return !this.isEquivalent(cur, prev, names);
    },

    //根据两个简单对象的值比较它们是否相同
    isEquivalent(a, b, include) {
      if (a != null && b != null) {
        let aProps = [];
        let aTemps = Object.getOwnPropertyNames(a);
        let bProps = [];
        let bTemps = Object.getOwnPropertyNames(b);

        //只考虑 include
        if (include instanceof Array) {
          // 数组
          for (let i = 0; i < include.length; i++) {
            let item = include[i];
            if (aTemps.includes(item)) {
              aProps.push(item);
            }
            if (bTemps.includes(item)) {
              bProps.push(item);
            }
          }
        } else if (include instanceof RegExp) {
          //正则
          for (let i = 0; i < aTemps.length; i++) {
            let item = aTemps[i];
            if (include.test(item)) {
              aProps.push(item);
            }
          }
          for (let i = 0; i < bTemps.length; i++) {
            let item = bTemps[i];
            if (include.test(item)) {
              bProps.push(item);
            }
          }
        } else {
          aProps = aTemps;
          bTemps = bTemps;
        }

        if (aProps.length != bProps.length) {
          return false;
        }

        for (let i = 0; i < aProps.length; i++) {
          let propName = aProps[i];
          if (a[propName] !== b[propName]) {
            return false;
          }
        }

        return true;
      } else if (a === b) {
        return true;
      } else {
        return false;
      }
    }
  },

  //监听参数变化
  watch: {
    cropParams(val, oldVal) {
      if (this.instance) {
        if (this.hasChanged(["src"], oldVal)) {
          this.instance.setImage(this.cropParams.src);
        }

        if (
          this.hasChanged(
            [
              "rotateSlider",
              "startAngle",
              "endAngle",
              "gapAngle",
              "lineationItemWidth"
            ],
            oldVal
          )
        ) {
          this.instance.initRotateSlider(this.cropParams);
        }

        if (
          this.hasChanged(["cropSizePercent"], oldVal) ||
          !this.isEquivalent(
            this.cropParams.positionOffset,
            oldVal.positionOffset,
            ["top", "left"]
          ) ||
          !this.isEquivalent(this.cropParams.size, oldVal.size, [
            "width",
            "height"
          ])
        ) {
          this.instance.updateBox(this.cropParams);
        }

        if (
          this.hasChanged(
            [
              "borderWidth",
              "borderColor",
              "boldCornerLen",
              "coverColor",
              "borderDraw",
              "coverDraw"
            ],
            oldVal
          )
        ) {
          this.instance.initBoxBorder(this.cropParams);
        }

        if (
          !this.isEquivalent(
            this.cropParams.funcBtns,
            oldVal.funcBtns,
            /^[0-9]*$/
          )
        ) {
          this.instance.initFuncBtns(this.cropParams);
        }

        if (this.hasChanged(["scaleSlider", "maxScale"], oldVal)) {
          this.instance.initScaleSlider(this.cropParams);
        }

        if (this.hasChanged(["title"], oldVal)) {
          this.instance.initTitle(this.cropParams);
        }

        if (this.cropParams.visible == false) {
          this.instance.hide();
        } else {
          this.instance.show();
        }
      }
    }
  }
};
</script>

<style scoped>
</style>
